version: '3.3'
services:
  db:
    build: ./mysql
    image: mysql:5.7
    restart: always
    environment:
      HTTP_PROXY: http://proxy.ynet.yanmar.co.jp:8080
      HTTPS_PROXY: http://proxy.ynet.yanmar.co.jp:8080
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
